"""Deterministic third-party inventory and bundled-asset notices (P22.4).

The inventory is derived mechanically from the two audited lockfiles and
the metadata shipped inside the locked environment, so it can be
regenerated byte-for-byte and drifted against both the locks and the
actually distributed frontend assets.  It records metadata only: names,
versions, roles, license identifiers, and deterministic source
locations.  An entry is ``direct`` when any project dependency group in
the owning lockfile — runtime or development — names it, and
``transitive`` otherwise; ``direct`` therefore does not distinguish
runtime from development dependencies.

The repository is distributed under MIT.  The owner-approved delivery
targets are the source tree, wheel, and packaged frontend.  Python and
frontend lock entries are audited for compatibility even when they are not
bundled.  The final notice lists every actual bundled third-party asset;
today that is the two frontend font binaries.  Every fail-closed rule below
exists so notices and compatibility evidence cannot silently drift:

- every non-project Python lock package must resolve to exactly one installed
  dist-info at the identical version, except the committed name-and-version
  record for a platform-conditional package unavailable on the current host;
- every lock package must yield a license identifier through the closed
  fallback chain (PEP 639 expression, then the legacy license field via
  the committed normalization table, then the trove classifier via the
  committed classifier table, then the per-package verified override);
- every frontend lock entry must carry a license field whose SPDX
  identity resolves inside the closed audited set;
- every distributed frontend asset must be either a first-party build
  output or a mapped third-party font package;
- ordering is fully specified, and no host-specific path or timestamp
  may enter the output.
"""

from __future__ import annotations

import json
import re
import tomllib
from dataclasses import dataclass
from email.parser import Parser
from pathlib import Path
from typing import cast

INVENTORY_FORMAT = "paritygrid-third-party-inventory"
INVENTORY_VERSION = 1
PROJECT_LICENSE = "MIT"
DISTRIBUTION_TARGETS = ("source-tree", "wheel", "packaged-frontend")

_PROJECT_PACKAGE_NAME = "paritygrid"
_FRONTEND_DIST_RELPATH = "web/dist"
_BUNDLED_NOTICE_RELPATH = "web/dist/THIRD_PARTY_NOTICES.txt"

# Verified per-package license identifiers for packages whose metadata
# carries no PEP 639 expression.  Each entry was checked against the
# package's embedded license text or classifier at Phase 22: colorama and
# nodeenv ship three-clause BSD texts; defusedxml ships the PSF license;
# the remaining entries match their trove classifiers.
_PYTHON_LICENSE_OVERRIDES: dict[str, str] = {
    "colorama": "BSD-3-Clause",
    "defusedxml": "PSF-2.0",
    "duckdb": "MIT",
    "markdown-it-py": "MIT",
    "mdurl": "MIT",
    "nodeenv": "BSD-3-Clause",
    "pip-api": "Apache-2.0",
    "pip-audit": "Apache-2.0",
    "shellingham": "ISC",
    "sortedcontainers": "Apache-2.0",
    "tomli-w": "MIT",
}

# `uv.lock` is universal, while `uv sync` selects packages for the current
# platform. colorama is a Windows-only dependency of click, pytest, and
# typer, so a Linux environment correctly has no dist-info for it. Retain
# full universal-lock coverage with this deliberately narrow, version-pinned
# exception; its license identity comes from `_PYTHON_LICENSE_OVERRIDES`.
_PLATFORM_CONDITIONAL_MISSING_DISTS = frozenset({("colorama", "0.4.6")})

# Exact legacy license-field strings observed in the locked set, mapped to
# SPDX identifiers.  An unmapped string fails closed.
_LEGACY_LICENSE_STRINGS: dict[str, str] = {
    "Apache 2.0": "Apache-2.0",
    "BSD": "BSD-3-Clause",
    "ISC License": "ISC",
    "PSFL": "PSF-2.0",
}

# Closed set of SPDX identifiers that legitimately occur across the two
# audited lockfiles.  A Python license value must resolve into this set;
# anything else fails closed instead of being recorded blindly.
_KNOWN_SPDX_IDENTIFIERS = frozenset(
    {
        "0BSD",
        "Apache-2.0",
        "BSD-2-Clause",
        "BSD-3-Clause",
        "BlueOak-1.0.0",
        "CC-BY-4.0",
        "CC0-1.0",
        "ISC",
        "MIT",
        "MIT-0",
        "MPL-2.0",
        "OFL-1.1",
        "PSF-2.0",
        "Python-2.0",
    }
)
_SPDX_CONNECTOR_PATTERN = re.compile(r"^(?:AND|OR|WITH|\(|\))$")

# The owner-approved MIT distribution model permits the audited dependency
# licenses below when their individual attribution and notice obligations are
# preserved.  A license outside this closed policy is a hard failure rather
# than an implied compatibility decision.
_MIT_COMPATIBLE_LICENSES = _KNOWN_SPDX_IDENTIFIERS

# Trove classifiers accepted as license identity for packages with no
# expression and no license field.  The generic BSD classifier is absent:
# it cannot distinguish clause variants, so such a package must appear in
# the per-package override table instead and otherwise fails closed.
_TROVE_CLASSIFIER_LICENSES: dict[str, str] = {
    "License :: OSI Approved :: Apache Software License": "Apache-2.0",
    "License :: OSI Approved :: MIT License": "MIT",
}

# Distributed frontend assets that are third-party works: the variable
# font binaries bundled from the @fontsource-variable packages.  Keys are
# the font-family stems of the bundled file names.
_DISTRIBUTED_FONT_PACKAGES: dict[str, str] = {
    "inter": "@fontsource-variable/inter",
    "roboto-mono": "@fontsource-variable/roboto-mono",
}

_FONT_FILE_PATTERN = re.compile(r"^([a-z0-9-]+)-latin-wght-normal-[A-Za-z0-9_-]+\.woff2$")
_FIRST_PARTY_ASSET_PATTERN = re.compile(r"^assets/index-[A-Za-z0-9_-]+\.(?:js|css)$")


class NoticeInventoryError(ValueError):
    """The inventory inputs violate a fail-closed rule."""


@dataclass(frozen=True)
class InventoryInputs:
    """Resolved paths of every audited inventory source."""

    uv_lock_path: Path
    python_site_packages: Path
    package_lock_path: Path
    frontend_dist_path: Path


def _compatibility(expression: str) -> str:
    """Return the recorded MIT compatibility result for one SPDX expression."""
    identifiers = _spdx_identifiers(expression)
    if not identifiers or not identifiers <= _MIT_COMPATIBLE_LICENSES:
        raise NoticeInventoryError(
            f"license expression {expression!r} is not covered by the MIT compatibility policy"
        )
    return "compatible-with-notice-obligations"


def build_inventory(inputs: InventoryInputs) -> dict[str, object]:
    """Build the deterministic inventory document from audited inputs."""
    python_entries = _python_entries(inputs.uv_lock_path, inputs.python_site_packages)
    frontend_document = _read_json(inputs.package_lock_path)
    frontend_entries, frontend_by_name = _frontend_entries(frontend_document)
    distributed_assets = _distributed_assets(inputs.frontend_dist_path, frontend_by_name)
    return {
        "format": INVENTORY_FORMAT,
        "inventory_version": INVENTORY_VERSION,
        "project": {
            "license": PROJECT_LICENSE,
            "distribution_targets": list(DISTRIBUTION_TARGETS),
        },
        "sources": {
            "python_lock": "uv.lock",
            "python_metadata": ".venv site-packages dist-info",
            "frontend_lock": "web/package-lock.json",
            "frontend_distribution": _FRONTEND_DIST_RELPATH,
        },
        "python": python_entries,
        "frontend": frontend_entries,
        "distributed_assets": distributed_assets,
    }


def render_inventory(inventory: dict[str, object]) -> str:
    """Render the inventory as deterministic, host-independent JSON text."""
    return json.dumps(inventory, indent=2, sort_keys=True, ensure_ascii=False) + "\n"


def _read_json(path: Path) -> dict[str, object]:
    document = cast("object", json.loads(path.read_text(encoding="utf-8")))
    if not isinstance(document, dict):
        raise NoticeInventoryError(f"{path.name} is not a JSON object")
    return cast("dict[str, object]", document)


def _python_entries(uv_lock_path: Path, site_packages: Path) -> list[dict[str, object]]:
    lock_document = tomllib.loads(uv_lock_path.read_text(encoding="utf-8"))
    packages = cast("object", lock_document.get("package"))
    if not isinstance(packages, list):
        raise NoticeInventoryError("uv.lock has no package list")
    locked_packages = cast("list[object]", packages)
    project_entry = next(
        (
            cast("dict[str, object]", package)
            for package in locked_packages
            if isinstance(package, dict)
            and cast("dict[str, object]", package).get("name") == _PROJECT_PACKAGE_NAME
        ),
        None,
    )
    if project_entry is None:
        raise NoticeInventoryError("uv.lock does not describe the paritygrid project")
    direct_names = _project_direct_names(project_entry)

    installed = _installed_python_metadata(site_packages)
    entries: list[dict[str, object]] = []
    for package in locked_packages:
        if not isinstance(package, dict):
            raise NoticeInventoryError("uv.lock package list contains a non-table entry")
        record = cast("dict[str, object]", package)
        name = record.get("name")
        version = record.get("version")
        if not isinstance(name, str) or not isinstance(version, str):
            raise NoticeInventoryError("uv.lock package entry lacks name or version")
        if name == _PROJECT_PACKAGE_NAME:
            continue
        dist_info = installed.get(_normalize_name(name))
        if dist_info is None and (name, version) not in _PLATFORM_CONDITIONAL_MISSING_DISTS:
            raise NoticeInventoryError(f"locked package {name} has no installed dist-info metadata")
        if dist_info is not None and dist_info["version"] != version:
            raise NoticeInventoryError(
                f"locked package {name} is installed at {dist_info['version']}, "
                f"not at the locked {version}"
            )
        license_identity = _python_license_identity(name, dist_info)
        entry: dict[str, object] = {
            "name": name,
            "version": version,
            "role": "direct" if name in direct_names else "transitive",
            "license": license_identity.identifier,
            "license_source": license_identity.source,
            "compatibility": _compatibility(license_identity.identifier),
            "location": license_identity.location,
        }
        entries.append(entry)
    entries.sort(key=lambda entry: (str(entry["name"]).lower(), str(entry["version"])))
    return entries


def _project_direct_names(project_entry: dict[str, object]) -> frozenset[str]:
    names: set[str] = set()
    dependencies = project_entry.get("dependencies")
    if isinstance(dependencies, list):
        for dependency in cast("list[object]", dependencies):
            if isinstance(dependency, dict):
                dependency_name = cast("dict[str, object]", dependency).get("name")
                if isinstance(dependency_name, str):
                    names.add(dependency_name)
    dev_dependencies = project_entry.get("dev-dependencies")
    if isinstance(dev_dependencies, dict):
        for group in cast("dict[str, object]", dev_dependencies).values():
            if isinstance(group, list):
                for dependency in cast("list[object]", group):
                    if isinstance(dependency, dict):
                        dependency_name = cast("dict[str, object]", dependency).get("name")
                        if isinstance(dependency_name, str):
                            names.add(dependency_name)
    return frozenset(names)


@dataclass(frozen=True)
class _LicenseIdentity:
    identifier: str
    source: str
    location: str | None


def _installed_python_metadata(site_packages: Path) -> dict[str, dict[str, object]]:
    installed: dict[str, dict[str, object]] = {}
    for dist_info in sorted(site_packages.glob("*.dist-info")):
        if not dist_info.is_dir():
            continue
        metadata = Parser().parsestr(
            (dist_info / "METADATA").read_text(encoding="utf-8", errors="replace")
        )
        name = metadata["Name"]
        version = metadata["Version"]
        if not name or not version:
            raise NoticeInventoryError(
                f"dist-info directory {dist_info.name} lacks name or version metadata"
            )
        classifiers = [
            value for value in (metadata.get_all("Classifier") or []) if "License" in value
        ]
        record: dict[str, object] = {
            "version": version,
            "license_expression": metadata["License-Expression"],
            "license_field": metadata["License"],
            "license_classifiers": classifiers,
            "home_page": metadata["Home-Page"],
        }
        installed[_normalize_name(name)] = record
    return installed


def _normalize_name(name: str) -> str:
    """Normalize a distribution name for matching (PEP 503)."""
    return re.sub(r"[-_.]+", "-", name).lower()


def _python_license_identity(name: str, dist_info: dict[str, object] | None) -> _LicenseIdentity:
    override = _PYTHON_LICENSE_OVERRIDES.get(name)
    if override is not None:
        return _LicenseIdentity(
            override,
            "verified-override",
            _home_page(dist_info) if dist_info is not None else None,
        )
    if dist_info is None:
        raise NoticeInventoryError(f"locked package {name} has no installed dist-info metadata")
    expression = dist_info["license_expression"]
    if isinstance(expression, str) and expression:
        _validate_spdx_expression(name, expression)
        return _LicenseIdentity(expression, "license-expression", _home_page(dist_info))
    legacy = dist_info["license_field"]
    if isinstance(legacy, str) and legacy:
        mapped = _LEGACY_LICENSE_STRINGS.get(legacy, legacy)
        if mapped not in _KNOWN_SPDX_IDENTIFIERS:
            raise NoticeInventoryError(
                f"package {name} carries unmapped legacy license string {legacy!r}"
            )
        return _LicenseIdentity(mapped, "legacy-license-field", _home_page(dist_info))
    classifiers_value = dist_info["license_classifiers"]
    if isinstance(classifiers_value, list):
        classifiers = cast("list[object]", classifiers_value)
        if len(classifiers) == 1 and isinstance(classifiers[0], str):
            mapped = _TROVE_CLASSIFIER_LICENSES.get(classifiers[0])
            if mapped is not None:
                return _LicenseIdentity(mapped, "trove-classifier", _home_page(dist_info))
    raise NoticeInventoryError(
        f"package {name} has no license metadata that the inventory can record"
    )


def _spdx_identifiers(expression: str) -> frozenset[str]:
    """Extract the identifier set from a syntactically restricted SPDX expression."""
    return frozenset(
        token
        for token in expression.replace("(", " ( ").replace(")", " ) ").split()
        if not _SPDX_CONNECTOR_PATTERN.match(token)
    )


def _validate_spdx_expression(name: str, expression: str) -> None:
    """Require every identifier in an expression to be in the closed set."""
    for token in _spdx_identifiers(expression):
        if token not in _KNOWN_SPDX_IDENTIFIERS:
            raise NoticeInventoryError(
                f"package {name} carries license expression {expression!r} "
                f"with identifier {token!r} outside the audited set"
            )


def _home_page(dist_info: dict[str, object]) -> str | None:
    home_page = dist_info["home_page"]
    return home_page if isinstance(home_page, str) and home_page else None


def _frontend_entries(
    document: dict[str, object],
) -> tuple[list[dict[str, object]], dict[str, dict[str, object]]]:
    """Extract one record per distinct lockfile (name, version) pair.

    npm dependency trees legitimately install several versions of one
    package at nested locations, so records are keyed by name and
    version; a genuine conflict is one (name, version) pair carrying
    different license identity at different locations, which fails
    closed.
    """
    packages = document.get("packages")
    if not isinstance(packages, dict):
        raise NoticeInventoryError("package-lock.json has no packages map")
    package_map = cast("dict[str, object]", packages)
    root = package_map.get("")
    direct_names: set[str] = set()
    if isinstance(root, dict):
        root_record = cast("dict[str, object]", root)
        for field in ("dependencies", "devDependencies"):
            section = root_record.get(field)
            if isinstance(section, dict):
                direct_names.update(cast("dict[str, object]", section))
    records: dict[tuple[str, str], dict[str, object]] = {}
    hoisted: dict[str, tuple[str, str]] = {}
    for location, entry in package_map.items():
        if location == "" or not isinstance(entry, dict):
            continue
        record = cast("dict[str, object]", entry)
        name = _frontend_package_name(location)
        if name is None:
            raise NoticeInventoryError(
                f"package-lock.json entry location {location!r} is not a package path"
            )
        version = record.get("version")
        if not isinstance(version, str) or not version:
            raise NoticeInventoryError(f"package-lock.json entry {location!r} lacks a version")
        license_identifier = _frontend_license(name, record.get("license"))
        resolved = record.get("resolved")
        entry_record: dict[str, object] = {
            "name": name,
            "version": version,
            "role": "direct" if name in direct_names else "transitive",
            "license": license_identifier,
            "license_source": "lockfile",
            "compatibility": _compatibility(license_identifier),
            "location": resolved if isinstance(resolved, str) else None,
        }
        key = (name, version)
        existing = records.get(key)
        if existing is not None:
            if existing["license"] != license_identifier:
                raise NoticeInventoryError(
                    f"package-lock.json contains conflicting license metadata for {name}@{version}"
                )
        else:
            records[key] = entry_record
        if location == f"node_modules/{name}":
            hoisted[name] = key
    entries = sorted(
        records.values(),
        key=lambda entry: (str(entry["name"]).lower(), str(entry["version"])),
    )
    by_name = {name: records[key] for name, key in hoisted.items() if key in records}
    return entries, by_name


def _frontend_package_name(location: str) -> str | None:
    """Derive the package name from its node_modules path."""
    segment = location.rsplit("node_modules/", 1)[-1]
    if not segment or segment.startswith("/"):
        return None
    if segment.startswith("@"):
        scope, separator, rest = segment.partition("/")
        if not separator or not scope or "/" in rest:
            return None
        return segment
    return segment if "/" not in segment else None


def _frontend_license(name: str, license_value: object) -> str:
    if isinstance(license_value, str) and license_value:
        _validate_spdx_expression(name, license_value)
        return license_value
    if isinstance(license_value, list):
        identifiers = [
            item for item in cast("list[object]", license_value) if isinstance(item, str)
        ]
        if identifiers and len(identifiers) == len(cast("list[object]", license_value)):
            joined = " OR ".join(sorted(identifiers))
            _validate_spdx_expression(name, joined)
            return joined
    raise NoticeInventoryError(f"frontend package {name} carries no license field in the lockfile")


def _distributed_assets(
    frontend_dist_path: Path, frontend_by_name: dict[str, dict[str, object]]
) -> list[dict[str, object]]:
    assets: list[dict[str, object]] = []
    if not frontend_dist_path.is_dir():
        raise NoticeInventoryError("the committed frontend distribution is missing")
    distributed = sorted(p for p in frontend_dist_path.rglob("*") if p.is_file())
    for asset_path in distributed:
        relative = (
            Path(_FRONTEND_DIST_RELPATH) / asset_path.relative_to(frontend_dist_path)
        ).as_posix()
        if relative == _BUNDLED_NOTICE_RELPATH:
            # This generated notice is a first-party delivery wrapper around
            # the third-party attribution below; its byte identity is checked
            # by scripts/verify_third_party_notices.py.
            continue
        name = asset_path.name
        if _FIRST_PARTY_ASSET_PATTERN.match(asset_path.relative_to(frontend_dist_path).as_posix()):
            continue
        font_match = _FONT_FILE_PATTERN.match(name)
        if font_match is not None:
            package_name = _DISTRIBUTED_FONT_PACKAGES.get(font_match.group(1))
            if package_name is None:
                raise NoticeInventoryError(
                    f"distributed font asset {relative} has no mapped source package"
                )
            package = frontend_by_name.get(package_name)
            if package is None:
                raise NoticeInventoryError(
                    f"distributed font asset {relative} maps to {package_name}, "
                    "which is not in the audited lockfile"
                )
            package_version = package["version"]
            package_license = package["license"]
            if not isinstance(package_version, str) or not isinstance(package_license, str):
                raise NoticeInventoryError(
                    f"distributed font package {package_name} lacks version or license"
                )
            asset_record: dict[str, object] = {
                "path": relative,
                "package": package_name,
                "version": package_version,
                "license": package_license,
            }
            assets.append(asset_record)
            continue
        if name == "index.html":
            continue
        raise NoticeInventoryError(
            f"distributed asset {relative} is neither a first-party build output "
            "nor a mapped third-party work"
        )
    assets.sort(key=lambda asset: str(asset["path"]))
    return assets


def render_bundled_notices(inputs: InventoryInputs) -> str:
    """Render notices for every third-party asset shipped in the frontend.

    The font packages are installed from the lockfile before this generator
    runs.  Their own license files provide the copyright lines and verbatim
    OFL text, so this never substitutes a guessed template or network copy.
    """
    lock = _read_json(inputs.package_lock_path)
    entries, by_name = _frontend_entries(lock)
    del entries
    assets = _distributed_assets(inputs.frontend_dist_path, by_name)
    lines = [
        "ParityGrid third-party notices",
        "",
        f"Project license: {PROJECT_LICENSE}",
        "Distributed forms: source tree, wheel, and packaged frontend.",
        "",
        "This file accompanies the bundled third-party frontend assets. "
        "The complete locked dependency inventory and MIT compatibility "
        "evidence are in docs/generated/third-party-notices.json.",
    ]
    for asset in assets:
        package_name = asset["package"]
        version = asset["version"]
        license_identifier = asset["license"]
        if (
            not isinstance(package_name, str)
            or not isinstance(version, str)
            or not isinstance(license_identifier, str)
        ):
            raise NoticeInventoryError("bundled asset metadata is incomplete")
        package = by_name.get(package_name)
        if package is None or package.get("version") != version:
            raise NoticeInventoryError(
                f"bundled asset {asset['path']} has no locked package record"
            )
        location = package.get("location")
        if not isinstance(location, str) or not location:
            raise NoticeInventoryError(f"bundled package {package_name} has no source location")
        license_text = _bundled_font_license_text(inputs.frontend_dist_path, package_name)
        copyrights = _copyright_lines(license_text)
        if not copyrights:
            raise NoticeInventoryError(f"bundled package {package_name} has no copyright notice")
        lines.extend(
            (
                "",
                f"## {package_name} {version}",
                f"Bundled asset: {asset['path']}",
                f"Source: {location}",
                f"License: {license_identifier}",
                "Copyright notices:",
                *[f"- {line}" for line in copyrights],
                "",
                "License text:",
                license_text.rstrip(),
            )
        )
    return "\n".join(lines) + "\n"


def _bundled_font_license_text(frontend_dist_path: Path, package_name: str) -> str:
    web_root = frontend_dist_path.parent
    license_path = web_root / "node_modules" / Path(*package_name.split("/")) / "LICENSE"
    try:
        text = license_path.read_text(encoding="utf-8")
    except OSError as error:
        raise NoticeInventoryError(
            f"bundled package {package_name} has no readable LICENSE file"
        ) from error
    normalized = text.replace("\r\n", "\n").replace("\r", "\n")
    if not normalized.strip():
        raise NoticeInventoryError(f"bundled package {package_name} has an empty LICENSE file")
    return normalized


def _copyright_lines(license_text: str) -> tuple[str, ...]:
    # Package copyright notices precede the first blank paragraph.  Later
    # mentions of "Copyright Holder" belong to the license terms and are not
    # attribution statements for this particular bundled work.
    header = license_text.split("\n\n", maxsplit=1)[0]
    return tuple(
        line.strip() for line in header.splitlines() if line.strip().lower().startswith("copyright")
    )
