"""Stable application-facing infrastructure contracts."""

from paritygrid.application.ports.configuration import (
    MAX_PAGE_SIZE,
    MAX_PIPELINE_DESCRIPTION_LENGTH,
    ConfigurationDocument,
    ConfigurationRepositoryError,
    ConfigurationStorageError,
    ConfigurationStorageUnavailableError,
    ConnectorPage,
    ConnectorRecord,
    ConnectorRepository,
    ConnectorSecretReference,
    CorruptRepositoryRecordError,
    DuplicateRecordError,
    InvalidRepositoryRequestError,
    PipelinePage,
    PipelineRecord,
    PipelineRepository,
    PipelineVersionConflictError,
    PipelineVersionPage,
    PipelineVersionRecord,
    RecordNotFoundError,
    RecordStateConflictError,
    StaleConnectorRevisionError,
    StaleRowVersionError,
    UnsafeConnectorConfigurationError,
    validate_page_limit,
)

__all__ = [
    "MAX_PAGE_SIZE",
    "MAX_PIPELINE_DESCRIPTION_LENGTH",
    "ConfigurationDocument",
    "ConfigurationRepositoryError",
    "ConfigurationStorageError",
    "ConfigurationStorageUnavailableError",
    "ConnectorPage",
    "ConnectorRecord",
    "ConnectorRepository",
    "ConnectorSecretReference",
    "CorruptRepositoryRecordError",
    "DuplicateRecordError",
    "InvalidRepositoryRequestError",
    "PipelinePage",
    "PipelineRecord",
    "PipelineRepository",
    "PipelineVersionConflictError",
    "PipelineVersionPage",
    "PipelineVersionRecord",
    "RecordNotFoundError",
    "RecordStateConflictError",
    "StaleConnectorRevisionError",
    "StaleRowVersionError",
    "UnsafeConnectorConfigurationError",
    "validate_page_limit",
]
